# Generated by Django 2.2.5 on 2019-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=800)),
                ('cv', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('CS', 'Computer Science'), ('BBA', 'Business Administration')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('HR', 'Human Resources'), ('F', 'Faculty')], max_length=2)),
            ],
        ),
    ]
