# Generated by Django 2.2.5 on 2019-09-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20190917_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administration'), ('F', 'Faculty')], max_length=5),
        ),
    ]
