# Generated by Django 2.2.5 on 2019-09-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20190918_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='static/cvs/'),
        ),
    ]
